---
# tasks file for pgadmin
- name: Render PG Admin CM
  template:
    src: pgadmin_configmap.j2.yaml
    dest: '{{ manifest_folder }}/pgadmin_configmap.yaml'
- name: Create Pgadmin CM
  shell:
    cmd: 'kubectl apply -f pgadmin_configmap.yaml -n {{ gisnamespace }}'
    chdir: '{{ manifest_folder }}'
- name: Render PG Admin Secret
  template:
    src: pgadmin_secret.j2.yaml
    dest: '{{ manifest_folder }}/pgadmin_secret.yaml'
- name: Create Pgadmin Secret
  shell:
    cmd: 'kubectl apply -f pgadmin_secret.yaml -n {{ gisnamespace }}'
    chdir: '{{ manifest_folder }}'
- name: Render server config cm
  template:
    src: server.j2.yaml
    dest: '{{ manifest_folder }}/server.yaml'
- name: Create server config cm
  shell:
    cmd: 'kubectl apply -f server.yaml -n {{ gisnamespace }}'
    chdir: '{{ manifest_folder }}'
- name: Render PG Admin manifest
  template:
    src: pgadmin_deployment.j2.yaml
    dest: '{{ manifest_folder }}/pgadmin_deployment.yaml'
- name: Create Pgadmin
  shell:
    cmd: 'kubectl apply -f pgadmin_deployment.yaml -n {{ gisnamespace }}'
    chdir: '{{ manifest_folder }}'
- name: Render PG Admin Service manifest
  template:
    src: pgadmin_service.j2.yaml
    dest: '{{ manifest_folder }}/pgadmin_service.yaml'
- name: Create Pgadmin
  shell:
    cmd: 'kubectl apply -f pgadmin_service.yaml -n {{ gisnamespace }}'
    chdir: '{{ manifest_folder }}'