apiVersion: v1
kind: ConfigMap
metadata:
  name: pga-configmap
  namespace: {{ gisnamespace }}
data:
  servers.json: |
    {
      "Servers": {
        "1": {
          "Name": "postgis",
          "Group": "Servers",
          "Host": "postgres",
          "Port": 5432,
          "MaintenanceDB": "postgres",
          "Username": "postgres",
          "PassFile": "{{user.admin.password}}",
          "SSLMode": "prefer"
        }
      }
    }
